Host = "127.0.0.1"
Level = "info"
Name = "sandbox"
Port = 1789
TokenExpiry = "168h0m0s"

[API]

  [API.GRPC]
    Hosts = ["api.sandbox.vega.xyz:3007", "api.n00.sandbox.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.sandbox.vega.xyz/graphql", "https://api.n00.sandbox.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.sandbox.vega.xyz", "https://api.n00.sandbox.vega.xyz"]

[Console]
  LocalPort = 1847
  URL = ""

[TokenDApp]
  LocalPort = 1848
  URL = ""
